name: Chapter 2

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      homedrive:
        description: 'The home drive on the machine'
        required: true
      log-level:
        description: 'Log level'
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tag:
        description: 'Apply tag after successful test run'
        required: true
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: choice # until `environment` is available
        required: true
        options: # placeholder options until repo environments are setup
          - development
          - staging
          - production
  repository_dispatch:
    types:
      [update, insert]
  
jobs:
  chapter-2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "👋 Hello World"
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
      - name: Workflow Dispatch Inputs
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Homedrive: ${{ inputs.homedrive }}"
          echo "Log level: ${{ inputs.log-level }}"
          echo "Tag source: ${{ inputs.tag }}"
          echo "Environment: ${{ inputs.environment }}"
      - name: Repository Dispatch Payload
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          echo "Payload: ${{ toJSON(github.event.client_payload) }}"
